import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { Geist, Geist_Mono } from "next/font/google";
import  Navbar  from "./components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Noah Arooji's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-dark text-white antialiased`}>
        <Navbar />
        {children}
        {/* Subtle static over every page so flat dark areas don't look empty */}
        <div aria-hidden="true" className="grain pointer-events-none fixed inset-0 z-30 print:hidden" />
        <Analytics />
      </body>
    </html>
  );
}
